export default {
  newGame: true,
  caraway: true,
  jack: true,
  joker: true,
  club: true,
  diamond: true,
  spade: true,
  heart: true,
  kadowaki: true,
  king: true,
  ccEnd: true,
  minimog: true,
  sacred: true,
  chicobo: true,
  alexander: true,
  doomtrain: true,
  pupu1: true,
  pupu2: true,
  pupu3: true,
  pupu4: true,
}