export default {
  cards: {
    play1Cards: [],
    play2Cards: [],
  },
  table: [
    [[null, null, null], [null, null, null], [null, null, null]],
    [[null, null, null], [null, null, null], [null, null, null]],
    [[null, null, null], [null, null, null], [null, null, null]],
  ],
  rules: {
    open: true,
    plus: false,
    same: false,
    elemental: false,
    sameWall: false,
    sudenDeath: false,
    random: false,
  },
  decks: {
    player: {
      deck1: Array(5).fill(6),
      deck2: Array(5).fill(7),
      deck3: Array(5).fill(8),
      deck4: Array(5).fill(9),
      deck5: Array(5).fill(10),
    },
    custom: {
      deck1: Array(5).fill(1),
      deck2: Array(5).fill(2),
      deck3: Array(5).fill(3),
      deck4: Array(5).fill(4),
      deck5: Array(5).fill(5),
    },
  },
  playerCards: {},
  streak: [0, 0, 0, 0],
  npcs: {
    balambGarden: {
      student1: {
        name: 'Student 1',
        cards: [1, 2, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      player1: {
        name: 'Player 1',
        cards: [1, 2],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      passerbyStudent: {
        name: 'Passerby 1',
        cards: [1, 2, 3],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      student2: {
        name: 'Student 2',
        cards: [1, 2, 3, 4],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      student3: {
        name: 'Student 3',
        cards: [1, 3, 4],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      kadowaki: {
        name: 'Dr. Kadowaki',
        cards: [1, 2, 3, 4, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      doorman: {
        name: 'Doorman',
        cards: [1, 2, 3, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      student4: {
        name: 'Student 4',
        cards: [1, 4],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      student5: {
        name: 'Student 5',
        cards: [1, 2, 4],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      student6: {
        name: 'Student 6',
        cards: [1, 2, 3, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      zell: {
        name: 'Zell',
        cards: [1, 2, 4, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      waitress: {
        name: 'Waitress',
        cards: [1, 2, 4, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      waitressSon: {
        name: 'Waitress',
        cards: [1, 3, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      quistisGroupie1: {
        name: 'Quistis Groupie 1',
        cards: [1, 3, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      quistisGroupie2: {
        name: 'Quistis Groupie 2',
        cards: [2, 5],
        special: [104],
        win: 0,
        loose: 0,
        tie: 0,
      },
      librarian: {
        name: 'Librarian',
        cards: [1, 2, 3],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      nida: {
        name: 'Nida',
        cards: [1, 2, 3, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      runningBoy: {
        name: 'Nida',
        cards: [1, 2, 3, 5],
        special: [81],
        win: 0,
        loose: 0,
        tie: 0,
      },
    },
    cardClub: {
      jack: {
        name: 'CC Jack',
        cards: [3, 4, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      joker: {
        name: 'CC Magician Joker',
        cards: [1, 2, 3, 4, 5, 6, 7],
        special: [91],
        win: 0,
        loose: 0,
        tie: 0,
      },
      club: {
        name: 'CC Knight Club',
        cards: [3, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      diamond: {
        name: 'CC Princess Diamond',
        cards: [3, 4, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      spade: {
        name: 'CC Prince Spade',
        cards: [3, 4, 6, 7],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      heart: {
        name: 'CC Queen of Heart - Xu',
        cards: [3, 5, 6, 7],
        special: [89],
        win: 0,
        loose: 0,
        tie: 0,
      },
      kadowaki: {
        name: 'Dr. Kadowaki',
        cards: [4, 5, 6, 7],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      king: {
        name: 'CC Master King - Quistis',
        cards: [1, 2, 3, 4, 5, 6, 7],
        special: [80],
        win: 0,
        loose: 0,
        tie: 0,
      },
    },
    balamb: {
      cardQueen: {
        name: 'Queen of Cards',
        cards: [1, 2],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      girl: {
        name: 'Girl in  entrance',
        cards: [1, 3, 4],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      boy: {
        name: 'Boy in Zell\'s house',
        cards: [1, 3, 4, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      stationChief: {
        name: 'Station Chief',
        cards: [1, 2],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      gardenStudent: {
        name: 'Garden Student',
        cards: [3, 4, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      womanWithDog: {
        name: 'Woman with dog',
        cards: [1, 2, 3, 4, 5],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      hotelOwner: {
        name: 'Hotel owner',
        cards: [4, 5],
        special: [93],
        win: 0,
        loose: 0,
        tie: 0,
      },
      hotelOwnerDaughter: {
        name: 'Hotel owner daughter',
        cards: [1, 4, 5, 6],
        special: [],
        win: 0,
        loose: 0,
        tie: 0,
      },
      maDincht: {
        name: 'Ma Dincht - Zell\'s mother',
        cards: [1, 2, 4, 5],
        special: [106],
        win: 0,
        loose: 0,
        tie: 0,
      },
    },
  },
};
