export default {
  random: {
    open: true,
    plus: false,
    same: false,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  balambGarden: {
    open: true,
    plus: false,
    same: false,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  balambTown: {
    open: true,
    plus: false,
    same: false,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  delingCity: {
    open: false,
    plus: false,
    same: true,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  galbadiaGarden: {
    open: false,
    plus: false,
    same: true,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  timber: {
    open: false,
    plus: false,
    same: true,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: false,
  },
  dollet: {
    open: false,
    plus: false,
    same: false,
    elemental: true,
    sameWall: false,
    suddenDeath: false,
    random: true,
  },
  fishermansHorizon: {
    open: false,
    plus: false,
    same: false,
    elemental: true,
    sameWall: false,
    suddenDeath: true,
    random: false,
  },
  shumiVillage: {
    open: false,
    plus: true,
    same: false,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: true,
  },
  trabiaGarden: {
    open: false,
    plus: true,
    same: false,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: true,
  },
  winhill: {
    open: false,
    plus: true,
    same: true,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: true,
  },
  edeasHouse: {
    open: false,
    plus: true,
    same: true,
    elemental: false,
    sameWall: false,
    suddenDeath: false,
    random: true,
  },
  esthar: {
    open: false,
    plus: false,
    same: false,
    elemental: true,
    sameWall: true,
    suddenDeath: false,
    random: false,
  },
}